### ISSUE TITLE
Proposal: Rename approval functions

### ISSUE THREAD

**Issue by kroggen** [aergoio/ARC1-Extensions#21]
The current functions names used on approval extensions are weird.

Example:

* `transferFromAll`
* `transferFromLtd`
* `burnFromAll`
* `burnFromLtd`

## Proposal

Rename them as this:

  `transferFromAll` -> `transferFrom`
  `transferFromLtd` -> `limitedTransferFrom`

  `burnFromAll` -> `burnFrom`
  `burnFromLtd -> limitedBurnFrom`

**Comment by ultrafellen** [comment]
I think it should be similar to OpenZeppelin as much as possible.
https://docs.openzeppelin.com/contracts/2.x/api/token/erc20

**Comment by kroggen** [comment]
Yeah, OpenZeppelin uses `transferFrom`

Solidity allows to have a single function for both cases.

In Lua we need 2 functions, so the proposal to name the other as `limitedTransferFrom `

It is better in English

And similar renaming for the burn related functions
